---
- name: Configure Linux Workloads
  hosts: linux_workload
  become: true
  vars:
    user_home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Copy Demo Server.sh 
      copy:
        src: "server.sh"
        dest: "/home/ubuntu/"
        mode: '0777'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      

    - name: Copy EC2 instance data file
      copy:
        src: ec2-instance-data.txt
        dest: "/home/ubuntu/ec2-instance-data.txt"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

